import './VerificationBadge.css';

const VerificationBadge = ({ verified = false }) => {
  if (verified === true) {
    return null;
  }

  return (
    <span 
      className="verification-badge" 
      title="Initial data generated by AI. Pending manual verification against official sources."
    >
      🤖 AI Generated<span className="badge-explanation"> - Pending manual verification</span>
    </span>
  );
};

export default VerificationBadge;
